### PR TITLE
Create buildallthethings.sh

### PR DESCRIPTION
**Pull request by Leppan**
Just pre-made coding.md into a script.

### CODE REVIEW

**Comment by KoczurekK** [comment]
What's the point of keeping script with those 4 first lines in repository which is (by design) cloned before building? I don't like that idea of copying script to run it locally. I won't merge it, maybe some other team member has different opinion about it, so I leave this PR open.

**Comment by Leppan** [comment]
*facepalm*
I just copy-pasted stuff... on mobile.

**Comment by KoczurekK** [comment]
I know what you have done there, but it makes no sense to me.
Btw you have a few mistakes in that script, it won't work, so even if adding it _does make sense_, not in this state.

**Comment by Leppan** [comment]
Welp, accidentally deleted the repository, so I'll have to remake it and close this. Sorry for the fuss.
The editor on mobile is terrible, glitchy, and literally unusable.

**Pull request closed without merging**
