### PR TITLE
New Updates - Error on close

### PR DESCRIPTION
**Pull request by vic3t3chn0**
Error on close.

### CODE REVIEW

**Comment by jsalatas** [comment]
Care to explain to us what is fixed here?  What is the bug any testing scenarios to verify your changes? 

Also why all these changes in make files?

**Comment by jhenstridge** [comment]
The diff shows that you've checked in a lot of generated files.

The semicolons added to the ends of the various `Q_*()` macros are unnecessary, and are generally not used in Qt code.  And I don't understand why you've commented out those parts of the `CMakeLists.txt` file: all of those dependencies should be available in Ubuntu, and you'll need them to get a working system.

And I'd strongly recommend against disabling the test suite: without it, how will you know that your changes are correct?

**Comment by vic3t3chn0** [comment]
I was trying to make the source compliant for debian Jessie and other
distribution

**Comment by jhenstridge** [comment]
While it might be possible to trim some of the dependencies, you'd be better off getting to a point where you can build and run the code as is.  Without that, how do you know whether what you're cutting is important?

And for what it is worth, you're not going to have a usable system without the `unity-shell-*` and `ubuntu-app-launch` pkg-config requirements you removed.  I doubt it will even build without them.

**Comment by jsalatas** [comment]
Guys, I'm closing this :)

**Pull request closed without merging**
